# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window222.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import prosses
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtGui import QImage, QPixmap
import os
from time import sleep
from pytube import YouTube
import threading
import requests
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1165, 467)
        MainWindow.setStyleSheet("QWidget {\n"
"    background-color: #121212;\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"    background-color: red;\n"
"    color: white;\n"
"    border: none;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"  border: 1px solid grey;\n"
"  background: white;\n"
"  selection-background-color: transperent;\n"
"}\n"
"QComboBox {\n"
"  background: white;\n"
"  selection-background-color:  black;\n"
"}\n"
"\n"
"\n"
"QLineEdit {\n"
"    background-color: white;\n"
"    color: black;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line_link = QtWidgets.QLineEdit(self.centralwidget)
        self.line_link.setGeometry(QtCore.QRect(30, 160, 461, 22))
        self.line_link.setObjectName("line_link")
        self.Down = QtWidgets.QPushButton(self.centralwidget)
        self.Down.setGeometry(QtCore.QRect(30, 210, 101, 51))
        self.Down.setObjectName("Down")
        self.Clear = QtWidgets.QPushButton(self.centralwidget)
        self.Clear.setGeometry(QtCore.QRect(380, 210, 101, 51))
        self.Clear.setObjectName("Clear")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(190, 230, 131, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.line_fail = QtWidgets.QLineEdit(self.centralwidget)
        self.line_fail.setGeometry(QtCore.QRect(80, 340, 331, 22))
        self.line_fail.setObjectName("line_fail")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 340, 55, 16))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: #121212;")
        self.label_2.setObjectName("label_2")
        self.choose = QtWidgets.QPushButton(self.centralwidget)
        self.choose.setGeometry(QtCore.QRect(430, 340, 93, 21))
        self.choose.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.choose.setObjectName("choose")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(30, 400, 491, 23))
        self.progressBar.setStyleSheet("color: rgb(255, 255, 255);")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(830, 150, 281, 281))
        self.textEdit.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, 0, 1201, 121))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("-516095198813lf2yjmbsw.png"))
        self.label.setObjectName("label")
        self.progressBar.raise_()
        self.title_line = QtWidgets.QTextEdit(self.centralwidget)
        self.title_line.setGeometry(QtCore.QRect(610, 80, 481, 31))
        self.title_line.setReadOnly(True)
        self.title_line.setObjectName("title_line")
        self.title_line.setStyleSheet("\n"
                                    "background-color: rgb(0, 0, 0);\n"
                                    "color: rgb(250, 250, 250);")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(550, 220, 241, 141))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.line_link.setPlaceholderText(_translate("MainWindow", "Paste the link "))
        self.Down.setText(_translate("MainWindow", "DOWNLOAD"))
        self.Clear.setText(_translate("MainWindow", "CLEAR"))
        self.comboBox.setItemText(0, _translate("MainWindow", "1080p"))
        self.comboBox.setItemText(1, _translate("MainWindow", "720p"))
        self.comboBox.setItemText(2, _translate("MainWindow", "480p"))
        self.comboBox.setItemText(3, _translate("MainWindow", "360p"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Audio"))
        self.line_fail.setPlaceholderText(_translate("MainWindow", "Fail path here"))
        self.label_2.setText(_translate("MainWindow", "Save in"))
        self.choose.setText(_translate("MainWindow", "choose"))
        self.line_fail.setText(os.path.expanduser(r'~\Downloads' + '\DowYouM'))



# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
